//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "users", table_name = "activity_user_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: String,
    pub last_played_game_title: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub last_played_game_time: Option<f64>,
    pub last_played_song_title: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub last_played_song_time: Option<f64>,
    pub last_played_song_artist: Option<String>,
    pub current_game_title: Option<String>,
    pub current_game_start_time: Option<DateTime>,
    pub current_song_title: Option<String>,
    pub current_song_artist: Option<String>,
    pub current_song_start_time: Option<DateTime>,
}

impl ActiveModelBehavior for ActiveModel {}
