//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "users", table_name = "activity_time_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: Date,
    #[sea_orm(column_type = "Double")]
    pub game_time: f64,
    pub game_count: i64,
    #[sea_orm(column_type = "Double")]
    pub music_time: f64,
    pub music_count: i64,
}

impl ActiveModelBehavior for ActiveModel {}
