//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "users", table_name = "activity_music_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub song_title: String,
    pub song_artist: String,
    pub play_count: i64,
    #[sea_orm(column_type = "Double")]
    pub time_played: f64,
}

impl ActiveModelBehavior for ActiveModel {}
