//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::activity_game_history::Entity as ActivityGameHistory;
pub use super::activity_music_history::Entity as ActivityMusicHistory;
pub use super::activity_time_history::Entity as ActivityTimeHistory;
pub use super::activity_user_data::Entity as ActivityUserData;
pub use super::user_assets::Entity as UserAssets;
pub use super::user_data::Entity as UserData;
pub use super::voice_message_history::Entity as VoiceMessageHistory;
