[workspace]
resolver = "2"
members = [
    "crates/app_state",
    "crates/dipped_dev",
    "crates/minecraft",
    "crates/r6_dipped_dev",
    "crates/role_eater",
    "crates/templates",
    "crates/utilities",
]
default-members = ["crates/dipped_dev", "crates/r6_dipped_dev"]

[workspace.package]
version = "2.1.0"
publish = false
edition = "2024"

[workspace.dependencies]
app_state = { path = "crates/app_state" }
dipped_dev = { path = "crates/dipped_dev" }
minecraft = { path = "crates/minecraft" }
r6_dipped_dev = { path = "crates/r6_dipped_dev" }
role_eater = { path = "crates/role_eater" }
templates = { path = "crates/templates" }
utilities = { path = "crates/utilities" }

# External crates
axum = { version = "0.8.8", features = ["http2", "macros", "ws"] }
chrono = { version = "0.4.43", features = ["now"] }
deadpool-diesel = { version = "0.6.1", features = ["postgres"] }
diesel = { version = "2.3.5", features = ["postgres", "chrono"] }
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
futures = "0.3.31"
glob = "0.3.3"
grass = "0.13.4"
maud = { version = "0.27.0", features = ["axum"] }
num-format = "0.4.4"
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = "0.7.18"
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["fs", "normalize-path"] }
