//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "guilds", table_name = "guild_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub guild_id: String,
    pub name: String,
    pub icon: Option<String>,
    pub banner: Option<String>,
    pub stat_exclusion_channels: Vec<String>,
}

impl ActiveModelBehavior for ActiveModel {}
