//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "guilds", table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: String,
    pub guild_id: String,
    pub creator_id: Option<String>,
    pub name: Option<String>,
    pub color: String,
    pub is_admin: bool,
}

impl ActiveModelBehavior for ActiveModel {}
