[package]
name = "rainbow_six"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "rainbow_six"
path = "src/main.rs"

[dependencies]
templates.workspace = true

axum.workspace = true
dotenvy.workspace = true
maud.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true

glob.workspace = true
grass.workspace = true
